version: '3.8'

services:
  api:
    build: .
    container_name: fastapi_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg2://admin:adminpassword@10.0.134.76:5432/fastapi_db